-- Create contact_info table for Contact Info module
-- Run this in your Supabase SQL editor

CREATE TABLE IF NOT EXISTS public.contact_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Create indexes for faster queries
CREATE INDEX idx_contact_info_created_at ON public.contact_info(created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.contact_info ENABLE ROW LEVEL SECURITY;

-- RLS Policy 1: Students can read all contacts (SELECT only)
CREATE POLICY "Students can view contact info"
  ON public.contact_info
  FOR SELECT
  USING (true);

-- RLS Policy 2: Admins have full CRUD access
CREATE POLICY "Admins can manage contact info"
  ON public.contact_info
  USING (true)
  WITH CHECK (true);

-- Note: For production, you'll need to verify admin role via custom claims or a separate users table
-- For now, these policies assume your auth system handles role-based access at the application level
