-- Run this SQL in your Supabase SQL editor if `notifications` table doesn't exist

CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_text TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  sender_role TEXT NOT NULL DEFAULT 'admin'
);

-- Optional: Grant select/insert/delete to anon (not recommended for production). Use RLS policies instead.
-- GRANT SELECT, INSERT, DELETE ON public.notifications TO anon;
