-- Create table for "Other Bookings" module
-- Run this in your Supabase SQL editor

CREATE TABLE IF NOT EXISTS public.other_bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT NOT NULL,
  booking_type VARCHAR(50) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  pickup_location TEXT NOT NULL,
  drop_location TEXT NOT NULL,
  passenger_count INT NOT NULL DEFAULT 1,
  notes TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,

);
-- Create indexes for faster queries
CREATE INDEX idx_other_bookings_student_id ON public.other_bookings(student_id);
CREATE INDEX idx_other_bookings_status ON public.other_bookings(status);

-- Optional: Grant select/insert/update/delete to anon if using client-side auth
-- GRANT SELECT, INSERT, UPDATE, DELETE ON public.other_bookings TO anon;
-- Note: Use Row Level Security (RLS) policies for production.
