-- Create complaints_feedback table
CREATE TABLE IF NOT EXISTS public.complaints_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_role VARCHAR(20) NOT NULL
    CHECK (user_role IN ('student', 'parent', 'driver', 'admin')),
  entry_type VARCHAR(20) NOT NULL
    CHECK (entry_type IN ('complaint', 'feedback')),
  category VARCHAR(50),
  subject VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  priority VARCHAR(10)
    CHECK (priority IN ('Low', 'Normal', 'High')),
  status VARCHAR(20) NOT NULL DEFAULT 'Pending'
    CHECK (status IN ('Pending', 'In Progress', 'Resolved', 'Closed')),
  admin_response TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_complaints_user_id
  ON public.complaints_feedback(user_id);

CREATE INDEX IF NOT EXISTS idx_complaints_status
  ON public.complaints_feedback(status);

CREATE INDEX IF NOT EXISTS idx_complaints_created_at
  ON public.complaints_feedback(created_at DESC);

-- Enable Row Level Security (no policies yet)
ALTER TABLE public.complaints_feedback ENABLE ROW LEVEL SECURITY;
